### ISSUE TITLE
Check if an array has extended properties

### ISSUE THREAD

**Issue by kurilovvo** [ldthomas/apg-lite#1]
The parser throws an error if the Array.prototype has extended methods

> Error: parser.js: Parser(): initializeCallbacks(): syntax callback 'extendedArrayMethod' not a rule or udt name

The patch attached

[_Check_if_the_Array_prototype_has_extended_properties.patch](https://github.com/user-attachments/files/16020046/_Check_if_the_Array_prototype_has_extended_properties.patch)

**Comment by ldthomas** [comment]
Can you give me an example of code that would return this error? I'm having a hard time seeing why the parser callbacks array would have extended methods unless it was being abused by the user. Its intended use is simply to hold pointers to callback functions for valid rule/udt names. Anything else is an error on the user's part.

**Comment by kurilovvo** [comment]
We have special requirements when processing arrays, so we needed to extend the prototype for the whole project. 

`Array.prototype.extendedArrayMethod = () => console.log('something');
`

as a result, when checking properties via `for in`, you get unnecessary properties

**Comment by ldthomas** [comment]
I obviously never anticipated anyone extending the Array prototype outside the scope of the parser. But I learned something about JavaScript object prototypes, so thank you for that. The modifications look simple enough so I will be happy to accommodate your project. I'll try to get a new release out within the next week or so. Thanks for using `apg-lite` and I hope it has otherwise been useful to you.

**Comment by kurilovvo** [comment]
Thank you

**Comment by ldthomas** [comment]
See version 1.04.
